#!/usr/bin/env sh

while true; do
  sleep 30

  cd "$IN_PATH"

  files=$(ls)
  for file in $files; do
    if [ -f "$OUT_PATH/unstable/$file" ]; then
      rm "$IN_PATH/$file"
    else
      mv "$IN_PATH/$file" "$OUT_PATH/mini-dinstall/incoming/"
    fi
  done
done
