#!/usr/bin/env sh

while true; do
  sleep 10

  cd /alloc/data/essi

  files=$(ls)
  for file in $files; do
    if [ -f /alloc/data/deb/unstable/$file ]; then
      rm /alloc/data/essi/$file
    else
      mv /alloc/data/essi/$file /alloc/data/deb/mini-dinstall/incoming/
    fi
  done
done
